services:
  pgrokd:
    image: "ghcr.io/pgrok/pgrokd:latest"
    restart: always
    volumes:
      - "./etc/pgrokd:/var/opt/pgrokd"
    ports:
      - "3320:3320"
      - "3000:3000"
      - "2222:2222"
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: pgrokd
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  nginx:
    image: nginx
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: "256M"
    restart: always
    ports:
      - 88:80
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  pg_data:
